### ISSUE TITLE
How do I obtain the original loc.json from the server

### ISSUE THREAD

**Issue by Neet-NXO** [ArtFect/BP-translate#1]
I tried to obtain JSON, but I got encrypted data. How can I decrypt it.

Thank you very much for your contribution
![image](https://github.com/ArtFect/BP-translate/assets/26018576/0ff0b5a4-3151-426c-9240-3d0d969eeb7b)

**Comment by ArtFect** [comment]
I don't really want to share the encryption key. Here is the original file
[texts_ja_JP.zip](https://github.com/ArtFect/BP-translate/files/11943743/texts_ja_JP.zip)

**Comment by Neet-NXO** [comment]
> I don't really want to share the encryption key. Here is the original file [texts_ja_JP.zip](https://github.com/ArtFect/BP-translate/files/11943743/texts_ja_JP.zip)

Okay, thank you very much

**Comment by ArtFect** [comment]
Encryption is aes256cbc(base64(data))

Key is 42777B2B69744B3625427C236D342E6279372429617E327A3D664D597A5E7E38
IV is specified in the response header. Also in base64
